version: '3.8'
services:
  bot:
    build: .
    container_name: pdf2imgtelegrambot
    env_file:
      - .envbot
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pdf2imgtelegramdb
    restart: always
    env_file:
      - .envdb
    ports:
      - "5462:5462"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './postgresdata'