version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: pdf2imgtelegramdb
    restart: always
    env_file:
      - .envdb
    volumes:
      - postgresdata:/var/lib/postgresql/data

  bot:
    build: .
    image: pdf2imgtelegram:latest
    container_name: pdf2imgtelegrambot
    restart: always
    depends_on:
      - db
    env_file:
      - .envbot

volumes:
  postgresdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/webuser/pdf2imgtelegram/postgresdata'